### ISSUE TITLE
any plan to publish to maven central?

### ISSUE THREAD

**Issue by timmyz** [nervosnetwork/ckb-sdk-java#112]
rt

**Comment by ashchan** [comment]
@duanyytop Any idea on this? Is it now easy to reference/use the SDK by specifying GitHub URL directly?

**Comment by duanyytop** [comment]
@ashchan  There is a way to create a GitHub repo as maven server to put our SDK, but no way to reference/use the SDK by specifying GitHub URL directly.

**Comment by ashchan** [comment]
> @ashchan There is a way to create a GitHub repo as maven server to put our SDK, but no way to reference/use the SDK by specifying GitHub URL directly.

Creating a repo for this purpose only seems too heavy. We'd rather publish to maven, or GitHub Package Registry.

**Comment by ashchan** [comment]
But again this is not current priority - unless that's so urgent/important that client apps couldn't use the SDK.

**Comment by duanyytop** [comment]
OK. I see.

@timmyz Could you use `console-{version}.jar` from GitHub Repository release now ?  If yes, we suggest you use the `console-{version}.jar` now. 

We hope to publish SDK to Maven Central when Nervos CKB has been stable or released for Mainnet.

**Comment by timmyz** [comment]
sure, thanks, for both of you. @duanyytop @ashchan

**Comment by duanyytop** [comment]
OK. I will close this issue. Thanks.
