### ISSUE TITLE
How to send a CKB transfer transaction?

### ISSUE THREAD

**Issue by wangke0809** [nervosnetwork/ckb-sdk-java#123]
Hi! How to send a CKB transfer transaction by using this SDK? Will this feature be added later?

**Comment by ashchan** [comment]
Please see https://github.com/nervosnetwork/ckb-sdk-java/blob/develop/console/src/test/java/org/nervos/ckb/WalletTest.java for a simple example.

**Comment by wangke0809** [comment]
Thanks!
