### ISSUE TITLE
How to get CODE_HASH?

### ISSUE THREAD

**Issue by ruanqunfeng** [nervosnetwork/ckb-sdk-java#124]
![image](https://user-images.githubusercontent.com/15098545/62452417-b6256600-b7a2-11e9-9ff1-6708de78c852.png)

**Comment by ruanqunfeng** [comment]
![image](https://user-images.githubusercontent.com/15098545/62452872-a22e3400-b7a3-11e9-8949-f5fc87f63b33.png)
This command will remove, so for this code
`String txHash = ((CkbTransactionHash)this.ckbService.computeTransactionHash(transaction).send()).getTransactionHash();`
how to replace

**Comment by classicalliu** [comment]
https://github.com/nervosnetwork/ckb-sdk-java/blob/v0.17.0/core/src/main/java/org/nervos/ckb/system/SystemContract.java#L13
the `CODE_HASH` means the default lock script code hash
It's the hash of genesis block's first transaction's second output's data

And the `_compute_transaction_hash` RPC is the only way to calculate transaction hash now.

**Comment by ruanqunfeng** [comment]
> https://github.com/nervosnetwork/ckb-sdk-java/blob/v0.17.0/core/src/main/java/org/nervos/ckb/system/SystemContract.java#L13
> the `CODE_HASH` means the default lock script code hash
> It's the hash of genesis block's first transaction's second output's data
> 
> And the `_compute_transaction_hash` RPC is the only way to calculate transaction hash now.

Thanks, if i want to calculate hash by code, how to achieve it?
