### ISSUE TITLE
When I unsign , what should the witness fill?

### ISSUE THREAD

**Issue by ruanqunfeng** [nervosnetwork/ckb-sdk-java#138]
![image](https://user-images.githubusercontent.com/15098545/63908143-ab33bd80-ca50-11e9-82dd-aafd8de71080.png)
What's the signature?

**Comment by duanyytop** [comment]
https://github.com/nervosnetwork/ckb-sdk-java/tree/develop/utils/src/main/java/org/nervos/ckb/crypto/secp256k1

Maybe above files can help you.
