### ISSUE TITLE
wrong expected_type_hash

### ISSUE THREAD

**Issue by piecezzz** [nervosnetwork/ckb-sdk-java#142]
v 0.19.0 release used wrong expected_type_hash.
While ruby-sdk use 
expected_type_hash = "0x68d5438ac952d2f584abf879527946a537e82c7f3c1cbf6d8ebf9767437d8e88"
but java computed "0xf6d0736d63b5ab0629ef574344bb59e4becb7874a5a170f8bb503509b3b2baf2"

and send_tx got
java.io.IOException: InvalidTx(ScriptFailure(InvalidCodeHash))

**Comment by duanyytop** [comment]
Fixed  https://github.com/nervosnetwork/ckb-sdk-java/releases/tag/v0.19.1
Thanks.
