### ISSUE TITLE
How to obtain balance

### ISSUE THREAD

**Issue by hoysoft** [nervosnetwork/ckb-sdk-java#150]
How to obtain wallet   balance

**Comment by duanyytop** [comment]
Now Java sdk does not support `getBalance` method, but we provide a live cells generator class.

We does not set more methods of wallet to sdk, so you can reference `TxGenerator.java` to compute balance of an account. 

Maybe the code https://github.com/nervosnetwork/ckb-sdk-java/blob/develop/core/src/main/java/org/nervos/ckb/transaction/TxGenerator.java#L110-L130  can help you.

**Comment by ashchan** [comment]
See the updated example: https://github.com/nervosnetwork/ckb-sdk-java/blob/develop/console/src/main/java/org/nervos/ckb/TransactionExample.java#L44
