### ISSUE TITLE
Update send transaction (capacity) example to support inputs from multiple lock scripts

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/ckb-sdk-java#169]
Currently the SDK collects inputs from a single address (and sign with the private key for that address). This task is to:

- [x] Provide multiple private keys when constructing a tx
- [x] Derive lock scripts for those private keys
- [x] Sign witnesses with these keys

## To sign inputs with multiple private keys

- [x] Update `Transaction.sign` and add `signInput` method
  - [x] The new `signInput(index, private key)` method signs the input at the specified index, with the provided private key
  - [x] When signing a single input, only the witness for that input should be signed and updated
  - [x] The current `sign` method can be updated to iterate over all inputs and sign each by using `signInput`
- ~[ ] Provide a default implementation for collect inputs for multiple (private keys ->) lock scripts/addresses~

**Comment by duanyytop** [comment]
https://github.com/nervosnetwork/ckb-sdk-java/pull/170
