### ISSUE TITLE
send_transaction has an error

### ISSUE THREAD

**Issue by ruanqunfeng** [nervosnetwork/ckb-sdk-java#220]
{"cellDeps":[{"depType":"dep_group","outPoint":{"index":"0x0","txHash":"0xbd864a269201d7052d4eb3f753f49f7c68b8edc386afc8bb6ef3e15a05facca2"}}],"headerDeps":[],"inputs":[{"previousOutput":{"index":"0x0","txHash":"0x19e827fb8bf5f3b1a056823f9e64df78fdfe3d10f99ecc0de560c215bfd07d6d"},"since":"0x0"}],"outputs":[{"capacity":"0x174876e800","lock":{"args":"0xfebc0705dc7f9a1e55874c4b8196051717a3b262","codeHash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","hashType":"type"}},{"capacity":"0x5d21cc5dc0","lock":{"args":"0x4d11235ddc00871218b98ed23cbc433f252e88b8","codeHash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","hashType":"type"}}],"outputsData":["0x","0x"],"version":"0x0","witnesses":["0x55000000100000005500000055000000410000002d53dc8f4b68bcf6d323bfa969f5773b52e8c40af2b5fcaad393b2a7ab6ecd8d47f891b1d6aa0d76d7f85c67d65dc833254c3167932b1fb6f981ecef3bed88f400"]}

java.io.IOException: RpcService method send_transaction error {"code":-3,"message":"Script(ValidationFailure(-31))"}

**Comment by duanyytop** [comment]
Firstly, please provide more log inforamtion or code.

`Script(ValidationFailure(-31)`  imply that your transaction signature has error, please check it.

**Comment by ruanqunfeng** [comment]
> Firstly, please provide more log information or code.
> 
> `Script(ValidationFailure(-31)` imply that your transaction signature has error, please check it.

List<CellOutput> cellOutputs = new ArrayList<>();
    cellOutputs.add(
            new CellOutput(
                    DecimalUtis.IntegerStringToHex("100000000000"),
                    new Script(
                            "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                            "0xfebc0705dc7f9a1e55874c4b8196051717a3b262",
                            Script.TYPE)));

    cellOutputs.add(
            new CellOutput(
                    DecimalUtis.IntegerStringToHex("399999000000"),
                    new Script(
                            "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                            "0x4d11235ddc00871218b98ed23cbc433f252e88b8",
                            Script.TYPE)));

    Transaction tx =
            new Transaction(
                    "0x0",
                    Collections.singletonList(
                            new CellDep(
                                    new OutPoint(
                                            "0xbd864a269201d7052d4eb3f753f49f7c68b8edc386afc8bb6ef3e15a05facca2", "0x0"),
                                    CellDep.DEP_GROUP)),
                    new ArrayList<>(),
                    Collections.singletonList(
                            new CellInput(
                                    new OutPoint(
                                            "0x19e827fb8bf5f3b1a056823f9e64df78fdfe3d10f99ecc0de560c215bfd07d6d", "0x0"),
                                    "0x0")),
                    cellOutputs,
                    Arrays.asList("0x", "0x"),
                    Collections.singletonList(new Witness()));

    BigInteger privateKey =
            Numeric.toBigInt("d7e047fb0d81a253a54d481128eb570f57f8b645107adbd76a4263cbd6a4e1f9");

    Transaction signedTx = tx.sign(privateKey);

**Comment by ruanqunfeng** [comment]
This is my code

public static String IntegerStringToHex(String integerString) {
        return "0x" + new BigInteger(integerString, 10).toString(16);
    }

**Comment by duanyytop** [comment]
https://github.com/nervosnetwork/ckb-system-scripts/blob/master/c/common.h  

We can know the error of -31 from above file is ERROR_PUBKEY_BLAKE160_HASH, and I want to know whether your cellDeps are right?

**Comment by ruanqunfeng** [comment]
> https://github.com/nervosnetwork/ckb-system-scripts/blob/master/c/common.h
> 
> We can know the error of -31 from above file is ERROR_PUBKEY_BLAKE160_HASH, and I want to know whether your cellDeps are right?

The cellDeps copy from other transaction.
![image](https://user-images.githubusercontent.com/15098545/68458246-401b1a00-023d-11ea-9023-619ef2408ee9.png)

**Comment by duanyytop** [comment]
We cannot promise other transaction is right and please reference example of `ckb-sdk` module to implement `sendTransaction`

**Comment by ruanqunfeng** [comment]
> We cannot promise other transaction is right and please reference example of `ckb-sdk` module to implement `sendTransaction`

I use this code "SingleKeySingleSigTxExample" to sendTransaction, but there also han an error 
send_transaction error {"code":-3,"message":"Transaction(InsufficientCellCapacity)"}

but my balance is sufficient.
I have 5,000 CKB, just send 1 CKB to ckt1qyq8l55qkcm7pvg6gu7lshrmcec9z72833yqqzlp2t and 1 CKB to ckt1qyqdvgxl76g0dxtrzxxhammresvy4nr52p8snvplfj

**Comment by duanyytop** [comment]
You cannot transaction 1 CKB , because any output will need byte size(capacity) to save in ckb blockchain. 

The min capacity is about 61 CKB, and you can try send 70 CKB to another address. 

Good luck.  Thanks

**Comment by ruanqunfeng** [comment]
> You cannot transaction 1 CKB , because any output will need byte size(capacity) to save in ckb blockchain.
> 
> The min capacity is about 61 CKB, and you can try to send 70 CKB to another address.
> 
> Good luck. Thanks

I change to the 70 CKB, but also has an error 
send_transaction error {"code":-3,"message":"Script(ValidationFailure(-31))"}
the SingleKeySingleSigTxExample is feasible？

**Comment by ruanqunfeng** [comment]
> Please check your private key and address of sender, and -31 tell us there are some errors in signature.

Thanks, my address is error.
