### ISSUE TITLE
java.io.IOException: Capacity not enough!

### ISSUE THREAD

**Issue by Reallyone** [nervosnetwork/ckb-sdk-java#239]

**Comment by Reallyone** [comment]
List<CellsWithAddress> cellsWithAddresses =
        txUtils.collectInputs(
            Collections.singletonList(MinerAddress), cellOutputs, feeRate, Sign.SIGN_LENGTH * 2);

**Comment by duanyytop** [comment]
You should check the balance of your address. Thanks
