### ISSUE TITLE
SingleSigWithIndexerTxExample  发送交易有问题

### ISSUE THREAD

**Issue by chenbingqian** [nervosnetwork/ckb-sdk-java#272]
在计算找零地址的时候，填充的capacity是0。导致在计算input的时候没有预留61个ckb。最后发送交易的时候提示余额不足

**Comment by duanyytop** [comment]
https://github.com/nervosnetwork/ckb-sdk-java/blob/develop/example/src/main/java/org/nervos/ckb/SingleSigWithIndexerTxExample.java#L100

Cell 收集完成后会更新 change capacity

**Comment by duanyytop** [comment]
any questions? If no questions, I will close the issue
