### ISSUE TITLE
get_transaction

### ISSUE THREAD

**Issue by simpleshark** [nervosnetwork/ckb-sdk-java#310]
request the get_transaction,that get the transaction info without address.
so how can i know which address receive the ckb coin

**Comment by duanyytop** [comment]
You can generate address from transaction output lock script and you can reference the [related code](https://github.com/nervosnetwork/ckb-sdk-java/blob/develop/ckb/src/main/java/org/nervos/ckb/utils/address/AddressGenerator.java)

**Comment by simpleshark** [comment]
> 
> 
> You can generate receive address from transaction output lock script and you can reference the [related code](https://github.com/nervosnetwork/ckb-sdk-java/blob/develop/ckb/src/main/java/org/nervos/ckb/utils/address/AddressGenerator.java)

that lock script like this "code_hash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"?

**Comment by duanyytop** [comment]
```
        "lock": {
                        "args": "0x",
                        "code_hash": "0x28e83a1277d48add8e72fadaa9248559e1b632bab2bd60b27955ebc4c03800a5",
                        "hash_type": "data"
                    },
```

[Address format RFC document](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0021-ckb-address-format/0021-ckb-address-format.md)

**Comment by simpleshark** [comment]
> 
> 
> ```
> "lock": {
>      "args": "0x",
>      "code_hash": "0x28e83a1277d48add8e72fadaa9248559e1b632bab2bd60b27955ebc4c03800a5",
>       "hash_type": "data"
> },
> ```
> 
> [Address format RFC document](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0021-ckb-address-format/0021-ckb-address-format.md)

thank you,i see
