### ISSUE TITLE
转账失败TransactionFailedToVerify报错

### ISSUE THREAD

**Issue by blockwu150** [nervosnetwork/ckb-sdk-java#573]
RpcService method send_transaction error {"code":-302,"message":"TransactionFailedToVerify: Verification failed Script(TransactionScriptError { source: Inputs[0].Lock, cause: ValidationFailure: see the error code -31 in the page https://nervosnetwork.github.io/ckb-script-error-codes/by-type-hash/9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8.html#-31 })"}

各位大佬，不同的cell 有不同的lock，导致单一签名失败，有没有example解决这个问题

**Comment by fjchen7** [comment]
Thanks for reporting. Can you post your code snippet?

**Comment by blockwu150** [comment]
package com.enation.app.javashop.service.nft.plugin;
//import static org.nervos.ckb.utils.Const.*;

import java.io.IOException;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.nervos.ckb.indexer.*;
import org.nervos.ckb.address.AddressUtils;
import org.nervos.ckb.address.Network;
import org.nervos.ckb.crypto.secp256k1.Sign;
import org.nervos.ckb.service.Api;
import org.nervos.ckb.transaction.*;
import org.nervos.ckb.type.Witness;
import org.nervos.ckb.type.cell.CellOutput;
import org.nervos.ckb.type.transaction.Transaction;
import org.nervos.ckb.type.transaction.TransactionWithStatus;
import org.nervos.ckb.utils.Numeric;
import org.nervos.ckb.utils.Utils;

/**
 * Copyright  2019 Nervos Foundation. All rights reserved.
 */
public class CKBAccountUtil {
    public static final String NODE_URL = "https://mainnet.ckbapp.dev/rpc";
public static final String CKB_INDEXER_URL = "https://mainnet.ckbapp.dev/indexer";

public static final BigInteger UnitCKB = new BigInteger("100000000");
public static final BigInteger MIN_CKB = new BigInteger("6100000000");
private static Api api;
private static CkbIndexerApi ckbIndexerApi;
private static List<String> SendPrivateKeys;
private static List<String> SendAddresses;
private static List<String> ReceiveAddresses;

static {
        api = new Api(NODE_URL, false);
ckbIndexerApi = new CkbIndexerApi(CKB_INDEXER_URL, false);
SendPrivateKeys =
                Arrays.asList("私钥");
SendAddresses = Arrays.asList("地址1");
ReceiveAddresses =
                Arrays.asList(
                        "地址2");
}

    public static void main(String[] args) throws Exception {
        AddressUtils utils = new AddressUtils(Network.MAINNET);
String lockHash = LockUtils.generateLockHashWithAddress("ckt1qyqrdsefa43s6m882pcj53m4gdnj4k440axqswmu83");

//        for (int i = 0; i < SendAddresses.size() - 1; i++) {
//            String testPublicKey = ECKeyPair.publicKeyFromPrivate(SendPrivateKeys.get(i));
//            String address = SendAddresses.get(i);
//            if (!address.equals(utils.generateFromPublicKey(testPublicKey))) {
//                System.out.println("Private key and address " + address + " are not matched");
//                return;
//            }
//        }

        System.out.println("Wait some time for ckb-indexer running");
System.out.println(
                "Before transferring, first sender's balance: "
                        + getBalance("地址1").divide(UnitCKB).toString(10)
                        + " CKB");

List<Receiver> receivers =
                Arrays.asList(
                        new Receiver(ReceiveAddresses.get(0), Utils.ckbToShannon(61))
                );

        String hash = sendCapacity(receivers, SendAddresses.get(0),SendPrivateKeys.get(0));
        System.out.println("Transaction hash: " + hash);

 waiting transaction into block, sometimes you should wait more seconds
        Thread.sleep(30000);

        System.out.println(
                "After transferring, first sender's balance: "
                        + getBalance("地址1").divide(UnitCKB).toString(10)
                        + " CKB");
}

    public static String getTxStatus(String txHash) throws IOException {
        TransactionWithStatus t = api.getTransaction(txHash);
return t.txStatus.status;//rejected
    }
    public static List getTxWitnesses(String txHash) throws IOException {
        TransactionWithStatus t = api.getTransaction(txHash);
return t.transaction.witnesses;
}

    public static BigInteger getBalance(String address) throws IOException {
        return new IndexerCollector(api, ckbIndexerApi).getCapacity(address);
}

    public static String sendCapacity(List<Receiver> receivers, String changeAddress, String privateKey)
            throws IOException {
        List<ScriptGroupWithPrivateKeys> scriptGroupWithPrivateKeysList = new ArrayList<>();
TransactionBuilder txBuilder = new TransactionBuilder(api);
IndexerCollector txUtils = new IndexerCollector(api, ckbIndexerApi);
List<CellOutput> cellOutputs = txUtils.generateOutputs(receivers, changeAddress);
txBuilder.addOutputs(cellOutputs);
// You can get fee rate by rpc or set a simple number
    BigInteger feeRate = BigInteger.valueOf(1024);
// initial_length = 2 * secp256k1_signature_byte.length
        // collectInputsWithIndexer method uses indexer rpc to collect cells quickly
        CollectResult collectResult =
                txUtils.collectInputs(SendAddresses, txBuilder.buildTx(), feeRate, Sign.SIGN_LENGTH * 2);

// update change cell output capacity after collecting cells if there is changeOutput
       if (Numeric.toBigInt(collectResult.changeCapacity).compareTo(BigInteger.ZERO) > 0) {
       cellOutputs.get(cellOutputs.size() - 1).capacity = collectResult.changeCapacity;
txBuilder.setOutputs(cellOutputs);
}

        int startIndex = 0;
for (CellsWithAddress cellsWithAddress : collectResult.cellsWithAddresses) {
            txBuilder.addInputs(cellsWithAddress.inputs);
for (int i = 0; i < cellsWithAddress.inputs.size(); i++) {
                txBuilder.addWitness(i == 0 ? new Witness(Witness.SIGNATURE_PLACEHOLDER) : "0x");
}
            if (cellsWithAddress.inputs.size() > 0) {
                scriptGroupWithPrivateKeysList.add(
                        new ScriptGroupWithPrivateKeys(
                                new ScriptGroup(
                                        NumberUtils.regionToList(startIndex, cellsWithAddress.inputs.size())),
                                Collections.singletonList(
                                        privateKey)));
startIndex += cellsWithAddress.inputs.size();
}
        }

        Secp256k1SighashAllBuilder signBuilder = new Secp256k1SighashAllBuilder(txBuilder.buildTx());

for (ScriptGroupWithPrivateKeys scriptGroupWithPrivateKeys : scriptGroupWithPrivateKeysList) {
            signBuilder.sign(
                    scriptGroupWithPrivateKeys.scriptGroup, scriptGroupWithPrivateKeys.privateKeys.get(0));
}
        Transaction tx = signBuilder.buildTx();
return api.sendTransaction(tx);
}
}

**Comment by blockwu150** [comment]
谢谢您的回复，您看一下我的代码

**Comment by fjchen7** [comment]
I think you are using the java-sdk of deprecated version 1.0.*. Indeed, it can't support signing transactions with different lock scripts in different cells. 

We do not plan to add features or change the deprecated version unless it has a significant impact. Please use the latest version [2.0.2](https://github.com/nervosnetwork/ckb-sdk-java/releases/tag/v2.0.2). You can find examples [here](https://github.com/nervosnetwork/ckb-sdk-java/tree/master/example/src/main/java/org/nervos/ckb/example) and learn how to sign and send the transaction with CKB and indexer.

**Comment by blockwu150** [comment]
好的，谢谢您，我升级一下

**Comment by blockwu150** [comment]
<img width="652" alt="d3b69cd5798fff6db2841bb2ae85616" src="https://user-images.githubusercontent.com/70093715/177479294-97f8f0b6-aa0c-4d08-85e8-2bd31aacafc2.png">
您看一下，这个2.0.2 为什么没下载到包呢？1.0.1就有，是不是应该有seriallization-2.0.2.jar这个文件

**Comment by blockwu150** [comment]
用的是maven 配置
<dependency>
  <groupId>org.nervos.ckb</groupId>
  <artifactId>serialization</artifactId>
  <version>2.0.2</version>
</dependency>

**Comment by blockwu150** [comment]
我手动下了，可以吗

**Comment by blockwu150** [comment]
您好请教一下，组装交易的时候如何保证 cota cell 的 capacity 不变呀
<img width="957" alt="3680a513a0b7117fe01091c12f5abed" src="https://user-images.githubusercontent.com/70093715/177533010-1173008c-a003-4ee3-9610-47740542d102.png">
多签这个例子似乎没有去操作cotacell，用了这个个多签脚本，您看一下！
这里面我觉得是通用的算法，它不会区别对待cotacell，就是这个有可能会存在我说的这个情况

**Comment by blockwu150** [comment]
This is in English, the content is the same
Hello, may I ask how to keep the capacity of the cota cell unchanged when assembling the transaction?
<img width="957" alt="3680a513a0b7117fe01091c12f5abed" src="https://user-images.githubusercontent.com/70093715/177535086-4ccf304c-9f80-494f-9a1c-8114cc2b7eed.png">
The example of multi-signature does not seem to operate cotacell. This multi-signature script is used. Take a look!
I think it is a general algorithm, it will not treat cotacell differently, that is, there may be the situation I mentioned

**Comment by fjchen7** [comment]
I may fail to get your point. You are trying to send a transaction from a singleSign address but you also use multisigScript which will only be used in multiSign cases.

Which cell's capacity do you want to keep unchanged? Can you describe your scenario completely from beginning to end?   It is good if you can give the rough transaction structure you want to construct and send.

**Comment by liuck8080** [comment]
If have any issue, please reopen it.
