### ISSUE TITLE
to support RPC method: get_transaction_and_witness_proof/verify_transaction_and_witness_proof

### ISSUE THREAD

**Issue by liuck8080** [nervosnetwork/ckb-sdk-java#633]
ckb-rpc v0.107.0 add new method:https://github.com/nervosnetwork/ckb/blob/v0.107.0/rpc/README.md#method-get_transaction_and_witness_proof, and https://github.com/nervosnetwork/ckb/blob/v0.107.0/rpc/README.md#method-verify_transaction_and_witness_proof, SDK should support these 2 methods

**Comment by blckngm** [comment]
Supported in #634.
